name: PyGuardIA CI/CD Pipeline

on:
  push:
    branches: [ "main" ]  # Se activa al subir cambios a la rama principal

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      # 1. Pruebas de Calidad (Higiene de código)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Test dependecies installation
        run: pip install bandit

      - name: Run static code analysis (Bandit)
        run: bandit -r src/ -f txt
      
      # 2. Login en Docker Hub (Usa Secrets para seguridad)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Construcción y Subida de la imagen
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Reemplaza 'tu-usuario' por tu nombre de Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/pyguardia:latest